environment: Development

registrySecret: "gcr-secret"
registry : "us-east1-docker.pkg.dev/baccoapp-358901/gcr-baccoapp/baccoapp-358901"

image:
  repository: baccoapp-user-management-api
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 15

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80